### PR TITLE
Added SMALL_FILES env var; fixes #6

### LINKED ISSUE #6: Service fails to start
I am getting the following error when trying to run this on a Synology NAS:

```
Exception in thread "Thread-0" java.lang.IllegalArgumentException: URI is not hierarchical | stdout
    at java.io.File.<init>(File.java:418)
    at com.tp_link.eap.util.g.a.a(SourceFile:47)
    at com.tp_link.eap.configuration.b.a(SourceFile:58)
    at com.tp_link.eap.util.o.c(SourceFile:443) | stdout
    at com.tp_link.eap.util.o.b(SourceFile:434)
    at com.tp_link.eap.start.f.run(SourceFile:35)
```

Folders have been set up and permissions have been set to everyone RW.

Ideas?

### PR DESCRIPTION
**Pull request by mbentley**
Signed-off-by: Matt Bentley <mbentley@mbentley.net>

### CODE REVIEW

**Comment by mbiebl** [comment]
afaics there are a couple of issues
- when the container is restarted, and `SMALL_FILES=true` is set, the `--smallfiles` command line option is duplicated
- when I shut down the container and set `SMALL_FILES=true` to `false`, an existing `--smallfiles` command line parameter is not removed on next start

**Comment by mbentley** [comment]
Thanks for reviewing.

- It shouldn't be duplicated; it wouldn't match a second time because i added `--smallfiles` to the beginning of the line so it would only match the first time
- You can't change environment variables of the container anyway unless you have a volume.  Recreating the container with a different option should reset the properties file as you would expect unless I am missing something.

**Comment by mbiebl** [comment]
> * It shouldn't be duplicated; it wouldn't match a second time because i added `--smallfiles` to the beginning of the line so it would only match the first time

Hm, right. Missed the '^'

> * You can't change environment variables of the container anyway unless you have a volume.  Recreating the container with a different option should reset the properties file as you would expect unless I am missing something.

I stop the container and start it again (not a restart, not recreating it). When starting it again, I can use different env vars, .e.g. I can easily modify `TZ` this way.

**Comment by mbentley** [comment]
How are you setting and changing the environment variables?  My expectation is that they are only set when the container is started `-e SMALL_FILES=true` and that is immutable for the life of the container.

**Comment by mbiebl** [comment]
I'm running this particular docker container on a synology nas. The webfrontend allows you to edit the TZ parameters when I shutdown the container. Maybe this is considered bad practice, dunno. 
But immuntable env vars are not something that are enforced by docker itself.

**Comment by mbentley** [comment]
I'm not sure how they are being changed then by Synology.  You can't change environment variables on a container without recreating the container.  Are you certain it isn't re-creating the container when changing them?  Only some resource options can be updated on a container:

```
$ docker container update --help

Usage:  docker container update [OPTIONS] CONTAINER [CONTAINER...]

Update configuration of one or more containers

Options:
      --blkio-weight uint16        Block IO (relative weight), between 10 and 1000, or 0 to disable (default 0)
      --cpu-period int             Limit CPU CFS (Completely Fair Scheduler) period
      --cpu-quota int              Limit CPU CFS (Completely Fair Scheduler) quota
      --cpu-rt-period int          Limit the CPU real-time period in microseconds
      --cpu-rt-runtime int         Limit the CPU real-time runtime in microseconds
  -c, --cpu-shares int             CPU shares (relative weight)
      --cpus decimal               Number of CPUs
      --cpuset-cpus string         CPUs in which to allow execution (0-3, 0,1)
      --cpuset-mems string         MEMs in which to allow execution (0-3, 0,1)
      --kernel-memory bytes        Kernel memory limit
  -m, --memory bytes               Memory limit
      --memory-reservation bytes   Memory soft limit
      --memory-swap bytes          Swap limit equal to memory plus swap: '-1' to enable unlimited swap
      --pids-limit int             Tune container pids limit (set -1 for unlimited)
      --restart string             Restart policy to apply when a container exits
```

**Comment by mbiebl** [comment]
I'm not sure how synology does it, but I tried the following:
- logged into the container via docker exec and created a flag file
- shut down the container
- changed TZ from Europe/Berling to UTC
- started the container again.

The changed TZ was picked up on start and the flag file was still there, indicating that the container was not recreated.

**Comment by mbentley** [comment]
Where did you create the file?  Just want to make sure it isn't some persistent volume where your file was saved between the container possibly being re-created. Either way, I am not sure it is worth taking into account anything that isn't possible with a vanilla Docker installation like changing environment variables.

**Comment by mbiebl** [comment]
No file, just clicky-pointy webinterface to configure the docker container. Remember, I'm still a noob when it comes to docker :-)

**Comment by mbentley** [comment]
I was curious how you went about doing this step and where that "flag file" was created:
> logged into the container via docker exec and created a flag file

**Comment by mbiebl** [comment]
> I was curious how you went about doing this step and where that "flag file" was created:
> 
> > logged into the container via docker exec and created a flag file

Ah, I created that file in '/root', not in the data, logs or work directory, as those are indeed volumes that are mounted inside the container.

**Pull request merged**
