### PR TITLE
Added docs about persistent data permissions; fixes #11

### LINKED ISSUE #11: Error starting up on Docker on OpenMediaVault
Pulled and installed the image
Added PUID and GUID to match owner of the 3 file systems

I get this at startup:
`SLF4J: com.tp_link.eap.util.m.a
SLF4J: The following set of substitute loggers may have been accessed
SLF4J: during the initialization phase. Logging calls during this
SLF4J: phase were not honored. However, subsequent logging calls to these
SLF4J: loggers will work as normally expected.
SLF4J: See also http://www.slf4j.org/codes.html#substituteLogger
Exception in thread "Thread-0" java.lang.IllegalArgumentException: URI is not hierarchical
	at java.io.File.<init>(File.java:418)
	at com.tp_link.eap.util.g.a.a(SourceFile:47)
	at com.tp_link.eap.configuration.b.a(SourceFile:58)
	at com.tp_link.eap.util.o.c(SourceFile:443)
	at com.tp_link.eap.util.o.b(SourceFile:434)
	at com.tp_link.eap.start.f.run(SourceFile:35)`

and then IO failing
`
2019-11-24 22:05:42,374 main ERROR Unable to create file /opt/tplink/EAPController/logs/server.log java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:574)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:554)
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:112)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:155)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:131)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.tp_link.eap.start.b.a.a.<clinit>(SourceFile:15)
	at com.tp_link.eap.start.EapLinuxMain.b(SourceFile:59)
	at com.tp_link.eap.start.EapLinuxMain.main(SourceFile:19)

2019-11-24 22:05:42,425 main ERROR Unable to inject fields into builder class for plugin type class org.apache.logging.log4j.core.appender.RollingFileAppender, element RollingFile. java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@59f99ea] unable to create manager for [/opt/tplink/EAPController/logs/server.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@27efef64[pattern=/opt/tplink/EAPController/logs/server_%d{yyyy-MM-dd}_%i.log.gz, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=true), SizeBasedTriggeringPolicy(size=20971520)]), strategy=DefaultRolloverStrategy(min=-2147483648, max=2147483647, useMax=false), advertiseURI=null, layout=%-d{yyyy-MM-dd HH:mm:ss} [%t] [%p]-[%F:%L] - %m%n]]
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:114)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:155)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:131)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.tp_link.eap.start.b.a.a.<clinit>(SourceFile:15)
	at com.tp_link.eap.start.EapLinuxMain.b(SourceFile:59)
	at com.tp_link.eap.start.EapLinuxMain.main(SourceFile:19)

2019-11-24 22:05:42,429 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:224)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:130)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:617)
	at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:634)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:229)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:152)
	at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:45)
	at org.apache.logging.log4j.LogManager.getContext(LogManager.java:194)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getContext(AbstractLoggerAdapter.java:122)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getContext(Log4jLoggerFactory.java:43)
	at org.apache.logging.log4j.spi.AbstractLoggerAdapter.getLogger(AbstractLoggerAdapter.java:46)
	at org.apache.logging.slf4j.Log4jLoggerFactory.getLogger(Log4jLoggerFactory.java:29)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:358)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.tp_link.eap.start.b.a.a.<clinit>(SourceFile:15)
	at com.tp_link.eap.start.EapLinuxMain.b(SourceFile:59)
	at com.tp_link.eap.start.EapLinuxMain.main(SourceFile:19)

2019-11-24 22:05:42,446 main ERROR Null object returned for RollingFile in Appenders.
2019-11-24 22:05:42,449 main ERROR Unable to locate appender "RollingFile" for logger config "root"
2019-11-24 22:05:42,450 main ERROR Unable to locate appender "RollingFile" for logger config "org"`

### PR DESCRIPTION
**Pull request by mbentley**
Signed-off-by: Matt Bentley <mbentley@mbentley.net>

### CODE REVIEW

**Comment by mbiebl** [comment]
Thanks for this documentation update.
You should also mention, that one has to create a data/db directory, otherwise mongod refuses to start.

**Comment by mbiebl** [comment]
I ran into this issue myself. Only after checking mongod.log I noticed what the problem was
```
Thu Jan 30 18:27:30 [initandlisten] MongoDB starting : pid=23 port=27217 dbpath=/opt/tplink/EAPController/data/db 64-bit host=9f88efa0876b
Thu Jan 30 18:27:30 [initandlisten] db version v2.2.2, pdfile version 4.5
Thu Jan 30 18:27:30 [initandlisten] git version: d1b43b61a5308c4ad0679d34b262c5af9d664267
Thu Jan 30 18:27:30 [initandlisten] build info: Linux ip-10-2-29-40 2.6.21.7-2.ec2.v1.2.fc8xen #1 SMP Fri Nov 20 17:48:28 EST 2009 x86_64 BOOST_LIB_VERSION=1_49
Thu Jan 30 18:27:30 [initandlisten] options: { bind_ip: "127.0.0.1", dbpath: "/opt/tplink/EAPController/data/db", journal: true, logappend: true, logpath: "/opt/tplink/EAPController/logs/mongod.log", nohttpinterface: true, pidfilepath: "/opt/tplink/EAPController/data/mongo.pid", port: 27217 }
Thu Jan 30 18:27:30 [initandlisten] exception in initAndListen: 10296 
*********************************************************************
 ERROR: dbpath (/opt/tplink/EAPController/data/db) does not exist.
 Create this directory or give existing directory in --dbpath.
 See http://dochub.mongodb.org/core/startingandstoppingmongo
*********************************************************************
, terminating
Thu Jan 30 18:27:30 dbexit: 
Thu Jan 30 18:27:30 [initandlisten] shutdown: going to close listening sockets...
Thu Jan 30 18:27:30 [initandlisten] shutdown: going to flush diaglog...
Thu Jan 30 18:27:30 [initandlisten] shutdown: going to close sockets...
Thu Jan 30 18:27:30 [initandlisten] shutdown: waiting for fs preallocator...
Thu Jan 30 18:27:30 [initandlisten] shutdown: lock for final commit...
Thu Jan 30 18:27:30 [initandlisten] shutdown: final commit...
Thu Jan 30 18:27:30 [initandlisten] shutdown: closing all files...
Thu Jan 30 18:27:30 [initandlisten] closeAllFiles() finished
Thu Jan 30 18:27:30 dbexit: really exiting now
```

**Comment by mbiebl** [comment]
Fwiw, the data/ directory is properly owned by 508:508. So it's not clear to me, why Omada Controller (or mongodb) can't just create this subdirectory itself.

**Comment by mbentley** [comment]
Thanks for the heads up.  I added an entrypoint script to handle that https://github.com/mbentley/docker-omada-controller/pull/18

**Pull request merged**
