### PR TITLE
Add support for running on Raspberry Pi

### PR DESCRIPTION
**Pull request by jeremyhiggs**
The bundled java and MongoDB binaries won't run on a Raspberry Pi. This PR installs the JDK and MongoDB, and links them into the EAP installation.

It also includes the previous PR adding a health check (mbentley/docker-omada-controller#22)

I've run this on a Raspberry Pi 3 with Ubuntu 18 64-bit as the host OS, and it works fine.

### CODE REVIEW

**Comment by mbentley** [comment]
Wow, nice investigative work to get this working!  I will say that instead of modifying the default Dockerfile, I would prefer a separate Dockerfile like `Dockerfile.v3.2.x-arm`.  I'd be somewhat cautious about pulling in different versions of Java and MongoDB from a longer term support point of view.   The Docker image gets a bit bloated as well (`3.2-test2` is the Dockerfile in the PR):

```
mbentley/omada-controller                                       3.2-test2           bfd64b184e5c        20 seconds ago      772MB
mbentley/omada-controller                                       3.2-test            fc47f34566d0        2 minutes ago       353MB
```

**Comment by jeremyhiggs** [comment]
That makes sense. I can also pin the versions to match whatever is being
used in the standard Omada release. Are you able to share what those are? I
don’t have a Linux x86 system to run the binaries on.


From: Matt Bentley <notifications@github.com> <notifications@github.com>
Reply: mbentley/docker-omada-controller
<reply@reply.github.com>
<reply@reply.github.com>
Date: 14 March 2020 at 3:59:59 pm
To: mbentley/docker-omada-controller
<docker-omada-controller@noreply.github.com>
<docker-omada-controller@noreply.github.com>
CC: Jeremy Higgs <jeremy.higgs@gmail.com> <jeremy.higgs@gmail.com>, Author
<author@noreply.github.com> <author@noreply.github.com>
Subject:  Re: [mbentley/docker-omada-controller] Add support for running on
Raspberry Pi (#24)

Wow, nice investigative work to get this working! I will say that instead

**Comment by mbentley** [comment]
Sure:
```
# ./mongod --version
db version v2.2.2, pdfile version 4.5
Sat Mar 14 07:42:15 git version: d1b43b61a5308c4ad0679d34b262c5af9d664267
```

```
# ./java -version
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)
```

**Comment by jeremyhiggs** [comment]
Currently testing this, will comment when I'm done.

**Comment by jeremyhiggs** [comment]
Confirmed that this works. Good to go.

**Comment by mbentley** [comment]
I"m sorry, I can't believe I forgot about this PR.  Thanks again for the contribution.

**Pull request merged**
