### PR TITLE
Support for 4.4.4

### PR DESCRIPTION
**Pull request by physhster**
4.4.4 is out, this branch adds support for it.

### CODE REVIEW

**Review by mbentley — CHANGES_REQUESTED** [review]
I'm remote right now but I assume the link works. Could you also update the readme?

**Comment by physhster** [comment]
Link is from this post: https://community.tp-link.com/en/business/forum/topic/245226 and resolves. I have put in a separate pull request for the readme file.

**Review by mbentley — APPROVED** [review]

**Comment by mbentley** [comment]
Thanks. LGTM

**Comment by mbentley** [comment]
Something isn't right - it's failing to build. I'll have to look later.

**Pull request merged**
